//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IU.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class AcceptRegister
    {
        public string AcceptRegisterID { get; set; }
        public string StudentID { get; set; }
        public string OpenSubjectID { get; set; }
        public string OpenClassID { get; set; }
        public Nullable<System.DateTime> RegisterDate { get; set; }
        public Nullable<int> OrderNum { get; set; }
        public Nullable<bool> Accepted { get; set; }
    
        public virtual OpenClassTBL OpenClassTBL { get; set; }
        public virtual OpenSubjectTBL OpenSubjectTBL { get; set; }
        public virtual StudentTBL StudentTBL { get; set; }
    }
}
