//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IU.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class AttendanceTBL
    {
        public string AttendanceID { get; set; }
        public string ClassID { get; set; }
        public string SemesterID { get; set; }
        public string StudentListID { get; set; }
        public string SubjectID { get; set; }
        public string SlotID { get; set; }
        public string Attendancer { get; set; }
        public System.DateTime DateAttendance { get; set; }
        public bool Attendance { get; set; }
        public string RoomID { get; set; }
    
        public virtual ClassTBL ClassTBL { get; set; }
        public virtual SemesterTBL SemesterTBL { get; set; }
        public virtual SlotTBL SlotTBL { get; set; }
        public virtual StudentTBL StudentTBL { get; set; }
        public virtual SubjectTBL SubjectTBL { get; set; }
    }
}
