//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IU.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class FeedBackTBL
    {
        public string Id { get; set; }
        public string Student { get; set; }
        public string Lecturer { get; set; }
        public string Quality { get; set; }
        public string OnTime { get; set; }
        public string Attitude { get; set; }
        public string Satisfaction { get; set; }
        public string Comments { get; set; }
        public Nullable<System.DateTime> FeedbackDate { get; set; }
    
        public virtual LecturerTBL LecturerTBL { get; set; }
        public virtual StudentTBL StudentTBL { get; set; }
        public virtual StudentTBL StudentTBL1 { get; set; }
    }
}
