//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IU.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class LecturerScheduleTBL
    {
        public string LecturerSchedule { get; set; }
        public string ClassID { get; set; }
        public string SemesterID { get; set; }
        public string SubjectID { get; set; }
        public string LecturerID { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
    
        public virtual ClassTBL ClassTBL { get; set; }
        public virtual LecturerTBL LecturerTBL { get; set; }
        public virtual SemesterTBL SemesterTBL { get; set; }
        public virtual SubjectTBL SubjectTBL { get; set; }
    }
}
