//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IU.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class ModeTBL
    {
        public string ModeID { get; set; }
        public string C3_5 { get; set; }
        public string C2_4 { get; set; }
        public string C3_5_6 { get; set; }
        public string C2_4_6 { get; set; }
        public string AllWeek { get; set; }
    }
}
