//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IU.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notification
    {
        public string Id { get; set; }
        public string MessageText { get; set; }
        public string ToUser { get; set; }
        public string Received { get; set; }
        public string Sent { get; set; }
        public Nullable<System.DateTime> MessageDate { get; set; }
    }
}
