//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IU.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class OpenClassTBL
    {
        public OpenClassTBL()
        {
            this.OpenSubjectTBLs = new HashSet<OpenSubjectTBL>();
        }
    
        public string OpenClassID { get; set; }
        public string ClassID { get; set; }
        public string RoomID { get; set; }
        public string SlotID { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string Creater { get; set; }
    
        public virtual ClassTBL ClassTBL { get; set; }
        public virtual ICollection<OpenSubjectTBL> OpenSubjectTBLs { get; set; }
    }
}
