//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IU.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class OpenSubjectTBL
    {
        public string OpenSubjectID { get; set; }
        public string SubjectID { get; set; }
        public string OpenClassID { get; set; }
        public Nullable<int> Credit { get; set; }
        public Nullable<decimal> Cost { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string Creater { get; set; }
    
        public virtual OpenClassTBL OpenClassTBL { get; set; }
        public virtual SubjectTBL SubjectTBL { get; set; }
    }
}
