//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IU.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class SlotTBL
    {
        public SlotTBL()
        {
            this.AttendanceTBLs = new HashSet<AttendanceTBL>();
        }
    
        public string SlotID { get; set; }
        public string SlotTime { get; set; }
        public string SlotName { get; set; }
        public Nullable<int> NumOfSlot { get; set; }
        public Nullable<int> TotalSlot { get; set; }
    
        public virtual ICollection<AttendanceTBL> AttendanceTBLs { get; set; }
    }
}
