//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IU.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentTBL
    {
        public StudentTBL()
        {
            this.AttendanceTBLs = new HashSet<AttendanceTBL>();
            this.StudentListTBLs = new HashSet<StudentListTBL>();
        }
    
        public string StudentID { get; set; }
        public string StudentName { get; set; }
        public bool StudentGender { get; set; }
        public System.DateTime StudentBirth { get; set; }
        public string StudentPhone { get; set; }
        public string StudentEmail { get; set; }
        public string ParentPhone { get; set; }
        public string UserID { get; set; }
    
        public virtual ICollection<AttendanceTBL> AttendanceTBLs { get; set; }
        public virtual ICollection<StudentListTBL> StudentListTBLs { get; set; }
    }
}
